execute pathogen#infect()

" vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

set nocompatible
filetype off

" ** required
Bundle 'gmarik/vundle'
" colors
Bundle 'gummesson/stereokai.vim'
" file types
Bundle "lepture/vim-jinja"
Bundle 'groenewege/vim-less'
" powerline
Bundle 'stephenmckinney/vim-solarized-powerline'
Bundle 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
" utilities
Bundle "Lokaltog/vim-easymotion"
Bundle "kien/ctrlp.vim.git"
Bundle "scrooloose/syntastic.git"
Bundle "vim-scripts/closetag.vim"

""
" Global config
""
set backupdir=~/.vim/backup,/tmp
set directory=~/.vim/backup,/tmp

set nowrap
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set number

colorscheme stereokai
syntax on
filetype plugin indent on

""
" File specific settings
""
au BufNewFile,BufRead *.sql setf pgsql

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

""
" Shortcuts
""
nmap \l :setlocal number!<CR>
nmap \o :set paste!<CR>
nmap \Q :q<CR>
nmap \q :nohlsearch<CR>

" split-it resizing with shift+arrow
nmap <silent> <s-down> :resize -5<cr>
nmap <silent> <s-up> :resize +5<cr>
nmap <silent> <s-left> :vertical resize -5<cr>
nmap <silent> <s-right> :vertical resize +5<cr>

" disable arrow keys for navigation
noremap <up> <nop>
noremap <down> <nop>
noremap <left> <nop>
noremap <right> <nop>

" navigate splits with with arrow keys
nnoremap <right> <c-w>l
nnoremap <left> <c-w>h
nnoremap <up> <c-w>k
nnoremap <down> <c-w>j

" split-it mapping
nmap <leader>-  :new<cr>
nmap <leader>\|  :vnew<cr>
nmap <leader>\  :rightbelow vnew<cr>
nmap <leader>_  :rightbelow new<cr>

map <leader><leader> <c-w>o
map <leader><leader><leader> :exit<cr>

set backspace=indent,eol,start

""
" Incremental search
""
set incsearch
set ignorecase
set smartcase
set hlsearch

""
" NERDTree
""
map <leader>n :NERDTreeToggle<cr>
let NERDTreeShowHidden=1
let NERDTreeIgnore = ['\.pyc$', '\.git', 'node_modules']
let NERDTreeQuitOnOpen = 1

""
" EasyMotion
""
let g:EasyMotion_leader_key = ','

""
" Powerline
""
set laststatus=2
set encoding=utf-8
let g:Powerline_theme='short'
let g:Powerline_colorscheme='solarized256'

""
" Ctrl-P Config
""
let g:ctrlp_map = '<Leader>t'
let g:ctrlp_match_window_bottom = 0
let g:ctrlp_match_window_reversed = 0
let g:ctrlp_custom_ignore = '\v\~$|\.(o|swp|pyc|wav|mp3|ogg|blend)$|(^|[/\\])\.(hg|git|bzr)($|[/\\])|__init__\.py'
let g:ctrlp_working_path_mode = 0
let g:ctrlp_dotfiles = 0
let g:ctrlp_switch_buffer = 0
